In [118]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('data.csv', skipfooter=18007, engine='python')
df = df.drop('ï»¿', axis=1)
df.head()

,Name,Age,Nationality,Potential,Club,Value,Preferred Foot,Work Rate,Position,Jersey Number,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,L. Messi,31,Argentina,94,FC Barcelona,â‚¬110.5M,Left,Medium/ Medium,RF,10,159lbs,84,95,70,90,86,97,93,94,87,96,91,86,91,95,95,85,68,72,59,94,48,22,94,94,75,96,33,28,26
1,Cristiano Ronaldo,33,Portugal,94,Juventus,â‚¬77M,Right,High/ Low,ST,7,183lbs,84,94,89,81,87,88,81,76,77,94,89,91,87,96,70,95,95,88,79,93,63,29,95,82,85,95,28,31,23
2,Neymar Jr,26,Brazil,93,Paris Saint-Germain,â‚¬118.5M,Right,High/ Medium,LW,10,150lbs,79,87,62,84,84,96,88,87,78,95,94,90,96,94,84,80,61,81,49,82,56,36,89,87,81,94,27,24,33
3,De Gea,27,Spain,93,Manchester United,â‚¬72M,Right,Medium/ Medium,GK,1,168lbs,17,13,21,50,13,18,21,19,51,42,57,58,60,90,43,31,67,43,64,12,38,30,12,68,40,68,15,21,13
4,K. De Bruyne,27,Belgium,92,Manchester City,â‚¬102M,Right,High/ High,RCM,7,154lbs,93,82,55,92,82,86,85,83,91,91,78,76,79,91,77,91,63,90,75,91,76,61,87,94,79,88,68,58,51

In [119]:
df = df.set_index(['Name'])
df = df.sort_values('Potential', ascending=False)
df.head(10)

,Age,Nationality,Potential,Club,Value,Preferred Foot,Work Rate,Position,Jersey Number,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
Name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
K. MbappÃ©,19,France,95,Paris Saint-Germain,â‚¬81M,Right,High/ Medium,RM,10,161lbs,77,88,77,82,78,90,77,63,73,91,96,96,92,87,83,79,75,83,71,78,62,38,88,82,70,86,34,34,32
L. Messi,31,Argentina,94,FC Barcelona,â‚¬110.5M,Left,Medium/ Medium,RF,10,159lbs,84,95,70,90,86,97,93,94,87,96,91,86,91,95,95,85,68,72,59,94,48,22,94,94,75,96,33,28,26
P. Dybala,24,Argentina,94,Juventus,â‚¬89M,Left,High/ Medium,LF,21,165lbs,82,84,68,87,88,92,88,88,75,92,87,83,91,86,85,82,75,80,65,88,48,32,84,87,86,84,23,20,20
Cristiano Ronaldo,33,Portugal,94,Juventus,â‚¬77M,Right,High/ Low,ST,7,183lbs,84,94,89,81,87,88,81,76,77,94,89,91,87,96,70,95,95,88,79,93,63,29,95,82,85,95,28,31,23
Neymar Jr,26,Brazil,93,Paris Saint-Germain,â‚¬118.5M,Right,High/ Medium,LW,10,150lbs,79,87,62,84,84,96,88,87,78,95,94,90,96,94,84,80,61,81,49,82,56,36,89,87,81,94,27,24,33
De Gea,27,Spain,93,Manchester United,â‚¬72M,Right,Medium/ Medium,GK,1,168lbs,17,13,21,50,13,18,21,19,51,42,57,58,60,90,43,31,67,43,64,12,38,30,12,68,40,68,15,21,13
J. Oblak,25,Slovenia,93,AtlÃ©tico Madrid,â‚¬68M,Right,Medium/ Medium,GK,1,192lbs,13,11,15,29,13,12,13,14,26,16,43,60,67,86,49,22,76,41,78,12,34,19,11,70,11,70,27,12,18
Gabriel Jesus,21,Brazil,92,Manchester City,â‚¬41M,Right,High/ High,ST,33,161lbs,66,84,74,76,72,86,76,54,66,85,87,85,92,86,91,78,77,84,68,73,73,32,88,77,78,82,53,23,19
Marco Asensio,22,Spain,92,Real Madrid,â‚¬54M,Left,High/ Medium,RW,10,168lbs,82,82,50,83,79,86,83,76,82,85,85,82,79,82,76,86,58,76,61,88,45,45,82,84,62,83,40,42,39
M. Å kriniar,23,Slovakia,92,Inter,â‚¬46.5M,Right,Medium/ High,LCB,37,176lbs,40,42,80,70,40,59,34,30,68,67,70,73,48,81,48,50,78,77,83,30,86,86,30,57,56,80,92,88,82

TypeError: argument of type 'float' is not iterable

In [116]:
len("â‚¬72M")

6